<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AF6N8QN" failures="1" tests="6" name="apiAutomationeleven.GoogleAddPlaceTest" time="4.462" errors="0" timestamp="27 Feb 2021 04:59:50 GMT" skipped="3">
  <testcase classname="apiAutomationeleven.GoogleAddPlaceTest" name="SpecBuilder" time="0.284">
    <failure message="expected [201] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at apiAutomationeleven.GoogleAddPlaceTest.SpecBuilder(GoogleAddPlaceTest.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SpecBuilder -->
  <testcase classname="apiAutomationeleven.GoogleAddPlaceTest" name="SpecBuilder" time="2.059">
    <skipped/>
  </testcase> <!-- SpecBuilder -->
  <testcase classname="apiAutomationeleven.GoogleAddPlaceTest" name="Print" time="1.152"/>
  <testcase classname="apiAutomationeleven.GoogleAddPlaceTest" name="SpecBuilder" time="0.360">
    <skipped/>
  </testcase> <!-- SpecBuilder -->
  <testcase classname="apiAutomationeleven.GoogleAddPlaceTest" name="SpecBuilder" time="0.320">
    <skipped/>
  </testcase> <!-- SpecBuilder -->
  <testcase classname="apiAutomationeleven.GoogleAddPlaceTest" name="AddPlace" time="0.287"/>
</testsuite> <!-- apiAutomationeleven.GoogleAddPlaceTest -->
